### ISSUE TITLE
centrifuge-class died with signal 11 (SEGV)

### ISSUE THREAD

**Issue by ps-account** [DaehwanKimLab/centrifuge#124]
Hi all, 

I get a crash when running:

```
centrifuge --verbose -t --met 1 --met-stderr -q -p 1 -x $WORKDIR/abv \
 -1 $WORKDIR/1_unmrp_FW.fq -2 $WORKDIR/1_unmrp_RV.fq \
 --report-file $WORKDIR/centrifuge_report.tsv -S $WORKDIR/centrifuge.out
```

it correctly read my .cf files, just after finishing that it crashes however:

```
...
  Finished opening input files: 10:19:54
  Reading header: 10:19:54
Reading plen (27160): 10:19:54
Reading rstarts (0): 10:19:54
Reading ebwt (11730789632): 10:19:54
Reading fchr (5)
Reading ftab (1048577): 10:20:40
Reading eftab (20): 10:20:40
Reading offs (2199523043 64-bit words): 10:20:40
Headers:
    len: 35192368678
    bwtLen: 35192368679
    sz: 8798092170
    bwtSz: 8798092170
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 2199523043
    offsSz: 17596184344
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 91646794
    numLines: 91646794
    ebwtTotLen: 11730789632
    ebwtTotSz: 11730789632
    color: 0
    reverse: 0
Time loading forward index: 00:01:16
(ERR): centrifuge-class died with signal 11 (SEGV)


```
